const ASSET_ROOT = "/wiragro-assets";

export const WIRAGRO_HERO_ASSETS = {
  farmerDigital: `${ASSET_ROOT}/hero/hero-petani-digital.png`,
} as const;

export const WIRAGRO_ICON_ASSETS = {
  account: `${ASSET_ROOT}/icons/akun.png`,
  aiChat: `${ASSET_ROOT}/icons/ai-chat.png`,
  article: `${ASSET_ROOT}/icons/artikel.png`,
  bag: `${ASSET_ROOT}/icons/bag-karung.png`,
  cart: `${ASSET_ROOT}/icons/keranjang.png`,
  chili: `${ASSET_ROOT}/icons/cabai.png`,
  corn: `${ASSET_ROOT}/icons/jagung.png`,
  distributor: `${ASSET_ROOT}/icons/distributor.png`,
  education: `${ASSET_ROOT}/icons/edukasi.png`,
  empty: `${ASSET_ROOT}/icons/empty-state.png`,
  error: `${ASSET_ROOT}/icons/error.png`,
  fieldBounty: `${ASSET_ROOT}/icons/field-bounty.png`,
  fruitDrop: `${ASSET_ROOT}/icons/buah-rontok.png`,
  fungus: `${ASSET_ROOT}/icons/jamur-penyakit.png`,
  grid: `${ASSET_ROOT}/icons/grid-lainnya.png`,
  home: `${ASSET_ROOT}/icons/home.png`,
  horti: `${ASSET_ROOT}/icons/hortikultura.png`,
  leaf: `${ASSET_ROOT}/icons/leaf.png`,
  melon: `${ASSET_ROOT}/icons/melon.png`,
  nutrition: `${ASSET_ROOT}/icons/nutrisi.png`,
  onion: `${ASSET_ROOT}/icons/bawang.png`,
  palm: `${ASSET_ROOT}/icons/sawit.png`,
  pest: `${ASSET_ROOT}/icons/hama.png`,
  polybag: `${ASSET_ROOT}/icons/pot-polybag.png`,
  product: `${ASSET_ROOT}/icons/produk.png`,
  rice: `${ASSET_ROOT}/icons/padi.png`,
  root: `${ASSET_ROOT}/icons/akar.png`,
  search: `${ASSET_ROOT}/icons/cari.png`,
  seed: `${ASSET_ROOT}/icons/seed.png`,
  service: `${ASSET_ROOT}/icons/service.png`,
  shield: `${ASSET_ROOT}/icons/shield-proteksi.png`,
  soil: `${ASSET_ROOT}/icons/soil.png`,
  solution: `${ASSET_ROOT}/icons/solusi.png`,
  spark: `${ASSET_ROOT}/icons/spark-booster.png`,
  spray: `${ASSET_ROOT}/icons/spray.png`,
  sprout: `${ASSET_ROOT}/icons/sprout.png`,
  stunted: `${ASSET_ROOT}/icons/pertumbuhan-lambat.png`,
  tomato: `${ASSET_ROOT}/icons/tomat.png`,
  tool: `${ASSET_ROOT}/icons/tool.png`,
  track: `${ASSET_ROOT}/icons/lacak-pesanan.png`,
  tray: `${ASSET_ROOT}/icons/tray-semai.png`,
  video: `${ASSET_ROOT}/icons/video.png`,
  warning: `${ASSET_ROOT}/icons/warning.png`,
  water: `${ASSET_ROOT}/icons/water.png`,
  weed: `${ASSET_ROOT}/icons/gulma.png`,
  yellowLeaf: `${ASSET_ROOT}/icons/daun-kuning.png`,
} as const;

export const WIRAGRO_CATEGORY_ASSETS = {
  aiDiagnosis: `${ASSET_ROOT}/categories/ai-diagnosis.png`,
  agriTools: `${ASSET_ROOT}/categories/alat-pertanian.png`,
  benih: `${ASSET_ROOT}/categories/benih.png`,
  bibit: `${ASSET_ROOT}/categories/bibit.png`,
  decorativeField: `${ASSET_ROOT}/categories/decorative-field.png`,
  decorativeSeedling: `${ASSET_ROOT}/categories/decorative-seedling.png`,
  education: `${ASSET_ROOT}/categories/edukasi-pertanian.png`,
  educationAlt: `${ASSET_ROOT}/categories/edukasi-pertanian-2.png`,
  emptyProduct: `${ASSET_ROOT}/categories/empty-product.png`,
  errorProduct: `${ASSET_ROOT}/categories/error-product.png`,
  farmStoreNeeds: `${ASSET_ROOT}/categories/kebutuhan-toko.png`,
  layanan: `${ASSET_ROOT}/categories/layanan.png`,
  logisticsPartner: `${ASSET_ROOT}/categories/logistik-mitra.png`,
  mulchProtector: `${ASSET_ROOT}/categories/mulsa-pelindung.png`,
  nutritionBooster: `${ASSET_ROOT}/categories/nutrisi-perangsang.png`,
  postHarvestPackaging: `${ASSET_ROOT}/categories/pascapanen-kemasan.png`,
  soilAmendment: `${ASSET_ROOT}/categories/pembenah-tanah.png`,
  harvestTools: `${ASSET_ROOT}/categories/peralatan-panen.png`,
  pesticide: `${ASSET_ROOT}/categories/pestisida.png`,
  livestock: `${ASSET_ROOT}/categories/peternakan.png`,
  polybagContainer: `${ASSET_ROOT}/categories/polybag-wadah.png`,
  pupuk: `${ASSET_ROOT}/categories/pupuk.png`,
  sprayer: `${ASSET_ROOT}/categories/sprayer.png`,
} as const;

export type WiragroIconAssetKey = keyof typeof WIRAGRO_ICON_ASSETS;
export type WiragroCategoryAssetKey = keyof typeof WIRAGRO_CATEGORY_ASSETS;
